name: GHPAGES

on:
  push:
    branches:
        - melodic_gazebo-9
jobs:
  release:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Install dependencies
      run: |
        sudo apt install pandoc -y
        sudo apt install python3.7 -y
        sudo apt install python-pip
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sphinx documentation
      run: |
        make html
        touch build/html/.nojekyll

    - name: github pages deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
