name: GHPAGES

on:
    push:
        branches:
            - melodic_gazebo-9
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Software properties
      run: sudo apt-get install -y software-properties-common

    - name: repository universe
      run: sudo apt-add-repository universe
    
    - name: update
      run: sudo apt-get update
    
    - name: Install pandoc
      run: sudo apt-get -y install pandoc

    - name: Install python
      run: sudo apt-get -y install python3.7

    - name: Install pip
      run: sudo apt-get -y install python3-pip

    - name: Upgrade pip
      run: pip install -U pip

    - name: pythonpath export
      run: sudo apt-get -y install pandoc

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: change to docs directory and make
      run: |
        cd docs
        make html
        touch build/html/.nojekyll

    - name: greate gh-pages
      run: |
        git checkout gh-pages
        git checkout melodic_gazebo-9 docs/build/html
        ls
        git branch -a
