name: GHPAGES

on:
    push:
        branches:
            - melodic_gazebo-9
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Software properties
      run: sudo apt-get install -y software-properties-common

    - name: repository universe
      run: sudo apt-add-repository universe
    
    - name: update
      run: sudo apt-get update
    
    - name: Install pandoc
      run: sudo apt-get -y install pandoc

    - name: Install python
      run: sudo apt-get -y install python3.7

    - name: Install pip
      run: sudo apt-get -y install python3-pip

    - name: Upgrade pip
      run: pip install -U pip

    - name: pythonpath export
      run: sudo apt-get -y install pandoc

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: change to docs directory and make
      run: |
        cd docs
        make html
        touch build/html/.nojekyll
        git branch -a

    - name: greate gh-pages
      run: |
        git checkout gh-pages
        cp -r docs/build/html/* ./
        rm -rf docs/
        ls
        git branch -a

    - name: add commit push
      run: |
        git config --global user.email "rahulbhadani@email.arizona.edu"
        git config --global user.name "rahulbhadani"
        touch .nojekyll
        git add .
        git commit -m "Updating documenation"
        git push

